# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('mname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('birthday', models.CharField(max_length=250)),
                ('place_of_birth', models.CharField(max_length=250)),
                ('religion', models.CharField(max_length=250)),
                ('citizenship', models.CharField(max_length=250)),
                ('fathersname', models.CharField(max_length=250)),
                ('mothersname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('barangay', models.CharField(max_length=250)),
                ('municipality', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
